import dotenv from 'dotenv'

dotenv.config()

const ENV = process.env


const PORT = ENV.PORT
const CLIENT_URL = ENV.CLIENT_URL
const NODE_ENV = ENV.NODE_ENV

const MONGODB_URI = ENV.MONGODB_URI

const MONGODB_USERNAME = ENV.MONGODB_USERNAME
const MONGODB_PASSWORD = ENV.MONGODB_PASSWORD

const ELEVENLABS_API_KEY = ENV.ELEVENLABS_API_KEY
const GOOGLE_API_KEY = ENV.GOOGLE_API_KEY

export { PORT, CLIENT_URL, NODE_ENV, MONGODB_USERNAME, MONGODB_PASSWORD, MONGODB_URI, GOOGLE_API_KEY, ELEVENLABS_API_KEY }