import dotenv from 'dotenv'

dotenv.config()

const ENV = process.env


const PORT = ENV.PORT
const CLIENT_URL = ENV.CLIENT_URL
const NODE_ENV = ENV.NODE_ENV

const MONGODB_URI = ENV.MONGODB_URI

const MONGODB_USERNAME = ENV.MONGODB_USERNAME
const MONGODB_PASSWORD = ENV.MONGODB_PASSWORD

const ELEVENLABS_API_KEY = ENV.ELEVENLABS_API_KEY

const GOOGLE_API_KEY = ENV.GOOGLE_API_KEY
const OPENAI_API_KEY = ENV.OPENAI_API_KEY

const HEYGEN_API_KEY = ENV.HEYGEN_API_KEY
const HEYGEN_WEBHOOK_URL = ENV.HEYGEN_WEBHOOK_URL

const CLOUDINARY_CLOUD_NAME = ENV.CLOUDINARY_CLOUD_NAME
const CLOUDINARY_API_KEY = ENV.CLOUDINARY_API_KEY
const CLOUDINARY_SECRET_KEY = ENV.CLOUDINARY_SECRET_KEY

export {
    PORT,
    CLIENT_URL,
    NODE_ENV,
    MONGODB_USERNAME,
    MONGODB_PASSWORD,
    MONGODB_URI,
    GOOGLE_API_KEY,
    ELEVENLABS_API_KEY,
    OPENAI_API_KEY,
    HEYGEN_API_KEY,
    HEYGEN_WEBHOOK_URL,
    CLOUDINARY_CLOUD_NAME,
    CLOUDINARY_API_KEY,
    CLOUDINARY_SECRET_KEY
}